### ISSUE TITLE
Small typos in Andon user guide in andon.yml format

### ISSUE THREAD

**Issue by jaheikki** [tieto-andon/andon#1]
Typo1: build_path and run_if_conditions should not have dash (-) in front of them.
Robot Framework chapter:
- job: test1-firefox
   tasks:
    - task: mvn clean install -Drobot.browser=firefox -Drobot.remote_url=http://hub:4444/wd/hub -Drobot.url=https://my.service.com -Drobot.tag=Portal
    - build_path: .
    - run_if_conditions: passed

    --------------------
Typo2: run_if_conditions should be located in same level than task (excluding the dash + space).
Cucumber chapter:
    tests:
    go_cd_agent_props:
      - java:8
      - maven
    test_services:
      robot_framework: false
      cucumber: true
    stages:
      - stage: AcceptanceTest
        jobs:
          - job: run_tests
            build_path: .
            tasks:
              - task: mvn clean install
              - task: mvn site
                  run_if_conditions: any

**Comment by makelkal** [comment]
You are right. We are on it.

**Comment by TapioKoski** [comment]
Correcttion done
